services:

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - task-service
      - payment-service
      - notification-service

  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_USER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  task-service:
    build: ./services/task-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_TASK_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_DB_PASS}
      - APP_JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  payment-service:
    build: ./services/payment-service
    ports:
      - "8003:8003"
    environment:
      - DB_HOST=payment-postgres
      - DB_PORT=5432
      - DB_NAME=PaymentService
      - DB_USER=postgres
      - DB_PASSWORD=highway55
      - JWT_SECRET=${JWT_SECRET}
      - PAYHERE_MERCHANT_ID=${PAYHERE_MERCHANT_ID}
      - PAYHERE_MERCHANT_SECRET=${PAYHERE_MERCHANT_SECRET}
    env_file:
      - .env
    depends_on:
      payment-postgres:
        condition: service_healthy

  payment-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: PaymentService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: highway55
    volumes:
      - payment-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  notification-service:
    image: alpine:3.19
    command: sleep infinity
    ports:
      - "8004:8004"

volumes:
  payment-pgdata:
  postgres_data:
